package com.video.dao;

import com.video.model.NoteBoard;
import com.video.model.NoteBoardExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NoteBoardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noteboard
     *
     * @mbggenerated
     */
    int countByExample(NoteBoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noteboard
     *
     * @mbggenerated
     */
    int deleteByExample(NoteBoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noteboard
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noteboard
     *
     * @mbggenerated
     */
    int insert(NoteBoard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noteboard
     *
     * @mbggenerated
     */
    int insertSelective(NoteBoard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noteboard
     *
     * @mbggenerated
     */
    List<NoteBoard> selectByExample(NoteBoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noteboard
     *
     * @mbggenerated
     */
    NoteBoard selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noteboard
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") NoteBoard record, @Param("example") NoteBoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noteboard
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") NoteBoard record, @Param("example") NoteBoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noteboard
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NoteBoard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noteboard
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NoteBoard record);
}