package com.video.model;

public class Star {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column star.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column star.video_id
     *
     * @mbggenerated
     */
    private String videoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column star.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column star.star_time
     *
     * @mbggenerated
     */
    private String starTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column star.star_num
     *
     * @mbggenerated
     */
    private Integer starNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column star.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column star.id
     *
     * @return the value of star.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column star.id
     *
     * @param id the value for star.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column star.video_id
     *
     * @return the value of star.video_id
     *
     * @mbggenerated
     */
    public String getVideoId() {
        return videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column star.video_id
     *
     * @param videoId the value for star.video_id
     *
     * @mbggenerated
     */
    public void setVideoId(String videoId) {
        this.videoId = videoId == null ? null : videoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column star.user_id
     *
     * @return the value of star.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column star.user_id
     *
     * @param userId the value for star.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column star.star_time
     *
     * @return the value of star.star_time
     *
     * @mbggenerated
     */
    public String getStarTime() {
        return starTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column star.star_time
     *
     * @param starTime the value for star.star_time
     *
     * @mbggenerated
     */
    public void setStarTime(String starTime) {
        this.starTime = starTime == null ? null : starTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column star.star_num
     *
     * @return the value of star.star_num
     *
     * @mbggenerated
     */
    public Integer getStarNum() {
        return starNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column star.star_num
     *
     * @param starNum the value for star.star_num
     *
     * @mbggenerated
     */
    public void setStarNum(Integer starNum) {
        this.starNum = starNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column star.user_name
     *
     * @return the value of star.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column star.user_name
     *
     * @param userName the value for star.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }
}