package com.video.model;

public class Video {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.upload_time
     *
     * @mbggenerated
     */
    private String uploadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.upload_id
     *
     * @mbggenerated
     */
    private String uploadId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.upload_name
     *
     * @mbggenerated
     */
    private String uploadName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.belong_key
     *
     * @mbggenerated
     */
    private String belongKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.belong_value
     *
     * @mbggenerated
     */
    private String belongValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.detail
     *
     * @mbggenerated
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.video_url
     *
     * @mbggenerated
     */
    private String videoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.year
     *
     * @mbggenerated
     */
    private String year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.country
     *
     * @mbggenerated
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.star_num
     *
     * @mbggenerated
     */
    private Integer starNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.star_sum
     *
     * @mbggenerated
     */
    private Integer starSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.value
     *
     * @mbggenerated
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.average
     *
     * @mbggenerated
     */
    private Double average;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.img_url
     *
     * @mbggenerated
     */
    private String imgUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.id
     *
     * @return the value of video.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.id
     *
     * @param id the value for video.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.name
     *
     * @return the value of video.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.name
     *
     * @param name the value for video.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.upload_time
     *
     * @return the value of video.upload_time
     *
     * @mbggenerated
     */
    public String getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.upload_time
     *
     * @param uploadTime the value for video.upload_time
     *
     * @mbggenerated
     */
    public void setUploadTime(String uploadTime) {
        this.uploadTime = uploadTime == null ? null : uploadTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.upload_id
     *
     * @return the value of video.upload_id
     *
     * @mbggenerated
     */
    public String getUploadId() {
        return uploadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.upload_id
     *
     * @param uploadId the value for video.upload_id
     *
     * @mbggenerated
     */
    public void setUploadId(String uploadId) {
        this.uploadId = uploadId == null ? null : uploadId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.upload_name
     *
     * @return the value of video.upload_name
     *
     * @mbggenerated
     */
    public String getUploadName() {
        return uploadName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.upload_name
     *
     * @param uploadName the value for video.upload_name
     *
     * @mbggenerated
     */
    public void setUploadName(String uploadName) {
        this.uploadName = uploadName == null ? null : uploadName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.state
     *
     * @return the value of video.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.state
     *
     * @param state the value for video.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.belong_key
     *
     * @return the value of video.belong_key
     *
     * @mbggenerated
     */
    public String getBelongKey() {
        return belongKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.belong_key
     *
     * @param belongKey the value for video.belong_key
     *
     * @mbggenerated
     */
    public void setBelongKey(String belongKey) {
        this.belongKey = belongKey == null ? null : belongKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.belong_value
     *
     * @return the value of video.belong_value
     *
     * @mbggenerated
     */
    public String getBelongValue() {
        return belongValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.belong_value
     *
     * @param belongValue the value for video.belong_value
     *
     * @mbggenerated
     */
    public void setBelongValue(String belongValue) {
        this.belongValue = belongValue == null ? null : belongValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.detail
     *
     * @return the value of video.detail
     *
     * @mbggenerated
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.detail
     *
     * @param detail the value for video.detail
     *
     * @mbggenerated
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.video_url
     *
     * @return the value of video.video_url
     *
     * @mbggenerated
     */
    public String getVideoUrl() {
        return videoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.video_url
     *
     * @param videoUrl the value for video.video_url
     *
     * @mbggenerated
     */
    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl == null ? null : videoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.year
     *
     * @return the value of video.year
     *
     * @mbggenerated
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.year
     *
     * @param year the value for video.year
     *
     * @mbggenerated
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.country
     *
     * @return the value of video.country
     *
     * @mbggenerated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.country
     *
     * @param country the value for video.country
     *
     * @mbggenerated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.type
     *
     * @return the value of video.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.type
     *
     * @param type the value for video.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.star_num
     *
     * @return the value of video.star_num
     *
     * @mbggenerated
     */
    public Integer getStarNum() {
        return starNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.star_num
     *
     * @param starNum the value for video.star_num
     *
     * @mbggenerated
     */
    public void setStarNum(Integer starNum) {
        this.starNum = starNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.star_sum
     *
     * @return the value of video.star_sum
     *
     * @mbggenerated
     */
    public Integer getStarSum() {
        return starSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.star_sum
     *
     * @param starSum the value for video.star_sum
     *
     * @mbggenerated
     */
    public void setStarSum(Integer starSum) {
        this.starSum = starSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.value
     *
     * @return the value of video.value
     *
     * @mbggenerated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.value
     *
     * @param value the value for video.value
     *
     * @mbggenerated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.average
     *
     * @return the value of video.average
     *
     * @mbggenerated
     */
    public Double getAverage() {
        return average;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.average
     *
     * @param average the value for video.average
     *
     * @mbggenerated
     */
    public void setAverage(Double average) {
        this.average = average;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.img_url
     *
     * @return the value of video.img_url
     *
     * @mbggenerated
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.img_url
     *
     * @param imgUrl the value for video.img_url
     *
     * @mbggenerated
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }
}